title: RamDev
subtitle: Software Engineering at VCU
description: This is the webiste for RamDev, a software engineering CS club at VCU.
author: Darren Chan
email: ramdev@vcu.edu
avatar: assets/images/logo.svg

# You'll want to customize url and baseurl for your own site:
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site

# Social settings
facebook_url: https://www.facebook.com/RamDevVCU/
github_url: https://github.com/ramdevvcu
googleplus_url:
instagram_url:
linkedin_url:
pinterest_url:
slack_url: https://vcucs.slack.com
twitter_url:

# Google Analytics Tracking ID goes here:
google_analytics:

# The following settings are NECESSARY for the Prologue theme to run:
remote_theme: chrisbobbe/jekyll-theme-prologue
collections: [sections]
